import 'package:flutter/widgets.dart';

import '../l10n/generated/app_localizations_gen.dart';
import '../l10n/generated/app_localizations_gen_en.dart';
import '../l10n/generated/app_localizations_gen_zh.dart';

/// Thin compatibility wrapper around generated [L10n] classes.
///
/// Keeps the existing static API (AppLocalizations.someKey) so that the
/// 200+ call sites across the codebase require zero changes.  Internally
/// delegates to the ARB-generated [L10nEn] / [L10nZh] instances.
class AppLocalizations {
  AppLocalizations._();

  static L10n _l10n = L10nEn();

  /// Call once at startup and whenever the user switches language.
  static void setLocale(String language) {
    _l10n = language == 'Traditional Chinese' ? L10nZh() : L10nEn();
  }

  /// Expose the generated delegates for [MaterialApp].
  static List<LocalizationsDelegate<dynamic>> get localizationsDelegates =>
      L10n.localizationsDelegates;
  static List<Locale> get supportedLocales => L10n.supportedLocales;

  // ── simple getters ─────────────────────────────────────────────
  static String get appTitle => _l10n.appTitle;
  static String get homeTitle => _l10n.homeTitle;
  static String get welcomeBack => _l10n.welcomeBack;
  static String get newGroup => _l10n.newGroup;
  static String get history => _l10n.history;
  static String get historyComingSoon => _l10n.historyComingSoon;
  static String get testFirebase => _l10n.testFirebase;
  static String get firebaseSuccess => _l10n.firebaseSuccess;
  static String get firebaseFailed => _l10n.firebaseFailed;
  static String get savedGroups => _l10n.savedGroups;
  static String get viewAll => _l10n.viewAll;
  static String get noSavedGroups => _l10n.noSavedGroups;
  static String get createFirstGroupHint => _l10n.createFirstGroupHint;
  static String get createGroup => _l10n.createGroup;
  static String get players => _l10n.players;
  static String get createdAt => _l10n.createdAt;
  static String get edit => _l10n.edit;
  static String get start => _l10n.start;
  static String get allGroups => _l10n.allGroups;
  static String get editGroupComingSoon => _l10n.editGroupComingSoon;
  static String get scoreUpdated => _l10n.scoreUpdated;
  static String get playerSetupTitle => _l10n.playerSetupTitle;
  static String get groupName => _l10n.groupName;
  static String get groupNameHint => _l10n.groupNameHint;
  static String get groupNameError => _l10n.groupNameError;
  static String get playerName => _l10n.playerName;
  static String get playerNameHint => _l10n.playerNameHint;
  static String get addPlayer => _l10n.addPlayer;
  static String get minimumPlayers => _l10n.minimumPlayers;
  static String get duplicatePlayer => _l10n.duplicatePlayer;
  static String get saveGroup => _l10n.saveGroup;
  static String get saveAndPlay => _l10n.saveAndPlay;
  static String get cancel => _l10n.cancel;
  static String get remove => _l10n.remove;
  static String get playerList => _l10n.playerList;
  static String get groupSaved => _l10n.groupSaved;
  static String get groupSaveFailed => _l10n.groupSaveFailed;
  static String get minFan => _l10n.minFan;
  static String get maxFan => _l10n.maxFan;
  static String get noLimit => _l10n.noLimit;
  static String get fanLimitSettings => _l10n.fanLimitSettings;
  static String get gameMode => _l10n.gameMode;
  static String get hongKongMahjong => _l10n.hongKongMahjong;
  static String get taiwaneseMahjong => _l10n.taiwaneseMahjong;
  static String get baseTai => _l10n.baseTai;
  static String get taiValue => _l10n.taiValue;
  static String get tai => _l10n.tai;
  static String get scoreRecording => _l10n.scoreRecording;
  static String get round => _l10n.round;
  static String get of => _l10n.ofSeparator;
  static String get dealer => _l10n.dealer;
  static String get calculateScore => _l10n.calculateScore;
  static String get endGame => _l10n.endGame;
  static String get gameResults => _l10n.gameResults;
  static String get finalScores => _l10n.finalScores;
  static String get winner => _l10n.winner;
  static String get close => _l10n.close;
  static String get nextRound => _l10n.nextRound;
  static String get stats => _l10n.stats;
  static String get roundsPlayed => _l10n.roundsPlayed;
  static String get selfDrawn => _l10n.selfDrawn;
  static String get winningRate => _l10n.winningRate;
  static String get totalFan => _l10n.totalFan;
  static String get totalTai => _l10n.totalTai;
  static String get scoreCalculation => _l10n.scoreCalculation;
  static String get enterScores => _l10n.enterScores;
  static String get specialWinningCondition => _l10n.specialWinningCondition;
  static String get submit => _l10n.submit;
  static String get reset => _l10n.reset;
  static String get totalMustBeZero => _l10n.totalMustBeZero;
  static String get confirmSubmit => _l10n.confirmSubmit;
  static String get totalIs => _l10n.totalIs;
  static String get continueAnyway => _l10n.continueAnyway;
  static String get win => _l10n.win;
  static String get selfDraw => _l10n.selfDraw;
  static String get discard => _l10n.discard;
  static String get winningPlayer => _l10n.winningPlayer;
  static String get discardPlayer => _l10n.discardPlayer;
  static String get roundWind => _l10n.roundWind;
  static String get seatWind => _l10n.seatWind;
  static String get flowers => _l10n.flowers;
  static String get selectFlowers => _l10n.selectFlowers;
  static String get handPreviewArea => _l10n.handPreviewArea;
  static String get scanTiles => _l10n.scanTiles;
  static String get uploadPhoto => _l10n.uploadPhoto;
  static String get selectHand => _l10n.selectHand;
  static String get analyzingTiles => _l10n.analyzingTiles;
  static String get takePhotoHint => _l10n.takePhotoHint;
  static String get item => _l10n.item;
  static String get value => _l10n.value;
  static String get totalScore => _l10n.totalScore;
  static String get fanTitle => _l10n.fanTitle;
  static String get limit => _l10n.limit;
  static String get perPerson => _l10n.perPerson;
  static String get points => _l10n.points;
  static String get twConcealedSelfDraw => _l10n.twConcealedSelfDraw;
  static String get descConcealedSelfDraw => _l10n.descConcealedSelfDraw;
  static String get explConcealedSelfDraw => _l10n.explConcealedSelfDraw;
  static String get twProperWind => _l10n.twProperWind;
  static String get descProperWind => _l10n.descProperWind;
  static String get explProperWind => _l10n.explProperWind;
  static String get twOrdinaryWind => _l10n.twOrdinaryWind;
  static String get descOrdinaryWind => _l10n.descOrdinaryWind;
  static String get explOrdinaryWind => _l10n.explOrdinaryWind;
  static String get twDragonPong => _l10n.twDragonPong;
  static String get descTwDragonPong => _l10n.descTwDragonPong;
  static String get explTwDragonPong => _l10n.explTwDragonPong;
  static String get twEyeOf258 => _l10n.twEyeOf258;
  static String get descEyeOf258 => _l10n.descEyeOf258;
  static String get explEyeOf258 => _l10n.explEyeOf258;
  static String get twAllSimples => _l10n.twAllSimples;
  static String get descAllSimples => _l10n.descAllSimples;
  static String get explAllSimples => _l10n.explAllSimples;
  static String get twConcealedDragon => _l10n.twConcealedDragon;
  static String get descConcealedDragon => _l10n.descConcealedDragon;
  static String get explConcealedDragon => _l10n.explConcealedDragon;
  static String get twFiveConcealedPongs => _l10n.twFiveConcealedPongs;
  static String get descFiveConcealedPongs => _l10n.descFiveConcealedPongs;
  static String get explFiveConcealedPongs => _l10n.explFiveConcealedPongs;
  static String get twDeclaredReady => _l10n.twDeclaredReady;
  static String get descDeclaredReady => _l10n.descDeclaredReady;
  static String get explDeclaredReady => _l10n.explDeclaredReady;
  static String get twUnderTheSea => _l10n.twUnderTheSea;
  static String get descUnderTheSea => _l10n.descUnderTheSea;
  static String get explUnderTheSea => _l10n.explUnderTheSea;
  static String get twWrongFlower => _l10n.twWrongFlower;
  static String get descWrongFlower => _l10n.descWrongFlower;
  static String get explWrongFlower => _l10n.explWrongFlower;
  static String get twProperFlower => _l10n.twProperFlower;
  static String get descProperFlower => _l10n.descProperFlower;
  static String get explProperFlower => _l10n.explProperFlower;
  static String get twDealerBonus => _l10n.twDealerBonus;
  static String get twConsecutiveDealer => _l10n.twConsecutiveDealer;
  static String get twDeclaredReadyCondition => _l10n.twDeclaredReadyCondition;
  static String get ruleSelfDraw => _l10n.ruleSelfDraw;
  static String get ruleNoFlowers => _l10n.ruleNoFlowers;
  static String get ruleFlowerPlatform14 => _l10n.ruleFlowerPlatform14;
  static String get ruleFlowerPlatform58 => _l10n.ruleFlowerPlatform58;
  static String get ruleOwnFlower => _l10n.ruleOwnFlower;
  static String get ruleOwnSeason => _l10n.ruleOwnSeason;
  static String get rulePongOfWhite => _l10n.rulePongOfWhite;
  static String get rulePongOfGreen => _l10n.rulePongOfGreen;
  static String get rulePongOfRed => _l10n.rulePongOfRed;
  static String get ruleRoundWind => _l10n.ruleRoundWind;
  static String get ruleSeatWind => _l10n.ruleSeatWind;
  static String get ruleAllChows => _l10n.ruleAllChows;
  static String get ruleAllPongs => _l10n.ruleAllPongs;
  static String get ruleMixedOneSuit => _l10n.ruleMixedOneSuit;
  static String get rulePureOneSuit => _l10n.rulePureOneSuit;
  static String get ruleSmallThreeDragons => _l10n.ruleSmallThreeDragons;
  static String get ruleBigThreeDragons => _l10n.ruleBigThreeDragons;
  static String get ruleSmallFourWinds => _l10n.ruleSmallFourWinds;
  static String get ruleBigFourWinds => _l10n.ruleBigFourWinds;
  static String get ruleThirteenOrphans => _l10n.ruleThirteenOrphans;
  static String get ruleEightImmortals => _l10n.ruleEightImmortals;
  static String get ruleFlowerHand => _l10n.ruleFlowerHand;
  static String get ruleHiddenTreasure => _l10n.ruleHiddenTreasure;
  static String get ruleAllHonors => _l10n.ruleAllHonors;
  static String get ruleNineGates => _l10n.ruleNineGates;
  static String get ruleEighteenArhats => _l10n.ruleEighteenArhats;
  static String get ruleSevenPairs => _l10n.ruleSevenPairs;
  static String get ruleMigui => _l10n.ruleMigui;
  static String get descSevenPairs => _l10n.descSevenPairs;
  static String get descMigui => _l10n.descMigui;
  static String get explSevenPairs => _l10n.explSevenPairs;
  static String get explMigui => _l10n.explMigui;
  static String get ruleHeavenlyHand => _l10n.ruleHeavenlyHand;
  static String get ruleEarthlyHand => _l10n.ruleEarthlyHand;
  static String get ruleKong => _l10n.ruleKong;
  static String get ruleNone => _l10n.ruleNone;
  static String get east => _l10n.east;
  static String get south => _l10n.south;
  static String get west => _l10n.west;
  static String get north => _l10n.north;
  static String get home => _l10n.home;
  static String get rules => _l10n.rules;
  static String get gameRules => _l10n.gameRules;
  static String get settings => _l10n.settings;
  static String get confirm => _l10n.confirm;
  static String get delete => _l10n.delete;
  static String get save => _l10n.save;
  static String get yes => _l10n.yes;
  static String get no => _l10n.no;
  static String get ok => _l10n.ok;
  static String get error => _l10n.error;
  static String get success => _l10n.success;
  static String get loading => _l10n.loading;
  static String get retry => _l10n.retry;
  static String get language => _l10n.language;
  static String get theme => _l10n.theme;
  static String get logout => _l10n.logout;
  static String get confirmLogout => _l10n.confirmLogout;
  static String get langEnglish => _l10n.langEnglish;
  static String get langTraditionalChinese => _l10n.langTraditionalChinese;
  static String get lightMode => _l10n.lightMode;
  static String get darkMode => _l10n.darkMode;
  static String get themeMode => _l10n.themeMode;
  static String get about => _l10n.about;
  static String get aboutDesc => _l10n.aboutDesc;
  static String get copyright => _l10n.copyright;
  static String get feedback => _l10n.feedback;
  static String get feedbackContent => _l10n.feedbackContent;
  static String get privacyPolicy => _l10n.privacyPolicy;
  static String get privacyPolicyContent => _l10n.privacyPolicyContent;
  static String get confirmDeleteGroup => _l10n.confirmDeleteGroup;
  static String get gameInProgressTitle => _l10n.gameInProgressTitle;
  static String get gameInProgressContent => _l10n.gameInProgressContent;
  static String get startNewGame => _l10n.startNewGame;
  static String get resumeGame => _l10n.resumeGame;
  static String get backToGame => _l10n.backToGame;
  static String get playerStatsTitle => _l10n.playerStatsTitle;
  static String get recentGroups => _l10n.recentGroups;
  static String get mostPlayedGroups => _l10n.mostPlayedGroups;
  static String get editPlayers => _l10n.editPlayers;
  static String get setupPlayers => _l10n.setupPlayers;
  static String get enterGroupNameHint => _l10n.enterGroupNameHint;
  static String get confirmDelete => _l10n.confirmDelete;
  static String get deleteGroupWarning => _l10n.deleteGroupWarning;
  static String get totalGamesMatches => _l10n.totalGamesMatches;
  static String get descAllChows => _l10n.descAllChows;
  static String get explAllChows => _l10n.explAllChows;
  static String get descNoFlowers => _l10n.descNoFlowers;
  static String get explNoFlowers => _l10n.explNoFlowers;
  static String get descOwnSeason => _l10n.descOwnSeason;
  static String get explOwnSeason => _l10n.explOwnSeason;
  static String get descSelfDraw => _l10n.descSelfDraw;
  static String get explSelfDraw => _l10n.explSelfDraw;
  static String get ruleMenQianQing => _l10n.ruleMenQianQing;
  static String get descMenQianQing => _l10n.descMenQianQing;
  static String get explMenQianQing => _l10n.explMenQianQing;
  static String get ruleDragonWindPong => _l10n.ruleDragonWindPong;
  static String get descDragonWindPong => _l10n.descDragonWindPong;
  static String get explDragonWindPong => _l10n.explDragonWindPong;
  static String get ruleRobbingKong => _l10n.ruleRobbingKong;
  static String get descRobbingKong => _l10n.descRobbingKong;
  static String get explRobbingKong => _l10n.explRobbingKong;
  static String get ruleHaidilao => _l10n.ruleHaidilao;
  static String get descHaidilao => _l10n.descHaidilao;
  static String get explHaidilao => _l10n.explHaidilao;
  static String get ruleKongOnKong => _l10n.ruleKongOnKong;
  static String get descKongOnKong => _l10n.descKongOnKong;
  static String get explKongOnKong => _l10n.explKongOnKong;
  static String get ruleFlowerPlatform => _l10n.ruleFlowerPlatform;
  static String get descFlowerPlatform => _l10n.descFlowerPlatform;
  static String get explFlowerPlatform => _l10n.explFlowerPlatform;
  static String get ruleSevenFlowers => _l10n.ruleSevenFlowers;
  static String get descSevenFlowers => _l10n.descSevenFlowers;
  static String get explSevenFlowers => _l10n.explSevenFlowers;
  static String get descAllPongs => _l10n.descAllPongs;
  static String get explAllPongs => _l10n.explAllPongs;
  static String get descMixedOneSuit => _l10n.descMixedOneSuit;
  static String get explMixedOneSuit => _l10n.explMixedOneSuit;
  static String get ruleMixedTerminals => _l10n.ruleMixedTerminals;
  static String get descMixedTerminals => _l10n.descMixedTerminals;
  static String get explMixedTerminals => _l10n.explMixedTerminals;
  static String get descSmallThreeDragons => _l10n.descSmallThreeDragons;
  static String get explSmallThreeDragons => _l10n.explSmallThreeDragons;
  static String get descSmallFourWinds => _l10n.descSmallFourWinds;
  static String get explSmallFourWinds => _l10n.explSmallFourWinds;
  static String get descThirteenOrphans => _l10n.descThirteenOrphans;
  static String get explThirteenOrphans => _l10n.explThirteenOrphans;
  static String get ruleBlessingMan => _l10n.ruleBlessingMan;
  static String get ruleBlessingOfMan => _l10n.ruleBlessingOfMan;
  static String get descBlessingMan => _l10n.descBlessingMan;
  static String get explBlessingMan => _l10n.explBlessingMan;
  static String get descEarthlyHand => _l10n.descEarthlyHand;
  static String get explEarthlyHand => _l10n.explEarthlyHand;
  static String get descHeavenlyHand => _l10n.descHeavenlyHand;
  static String get explHeavenlyHand => _l10n.explHeavenlyHand;
  static String get descEighteenArhats => _l10n.descEighteenArhats;
  static String get explEighteenArhats => _l10n.explEighteenArhats;
  static String get descBigFourWinds => _l10n.descBigFourWinds;
  static String get explBigFourWinds => _l10n.explBigFourWinds;
  static String get descEightImmortals => _l10n.descEightImmortals;
  static String get explEightImmortals => _l10n.explEightImmortals;
  static String get descHiddenTreasure => _l10n.descHiddenTreasure;
  static String get explHiddenTreasure => _l10n.explHiddenTreasure;
  static String get ruleDoubleKong => _l10n.ruleDoubleKong;
  static String get descDoubleKong => _l10n.descDoubleKong;
  static String get explDoubleKong => _l10n.explDoubleKong;
  static String get descAllHonors => _l10n.descAllHonors;
  static String get explAllHonors => _l10n.explAllHonors;
  static String get rulePureTerminals => _l10n.rulePureTerminals;
  static String get descPureTerminals => _l10n.descPureTerminals;
  static String get explPureTerminals => _l10n.explPureTerminals;
  static String get descNineGates => _l10n.descNineGates;
  static String get explNineGates => _l10n.explNineGates;
  static String get descPureOneSuit => _l10n.descPureOneSuit;
  static String get explPureOneSuit => _l10n.explPureOneSuit;
  static String get descBigThreeDragons => _l10n.descBigThreeDragons;
  static String get explBigThreeDragons => _l10n.explBigThreeDragons;
  static String get totalHandsPlayed => _l10n.totalHandsPlayed;
  static String get noResultRate => _l10n.noResultRate;
  static String get statsWinRate => _l10n.statsWinRate;
  static String get statsSelfDraw => _l10n.statsSelfDraw;
  static String get statsRon => _l10n.statsRon;
  static String get statsDealIn => _l10n.statsDealIn;
  static String get selectDealer => _l10n.selectDealer;
  static String get startGame => _l10n.startGame;
  static String get gameOver => _l10n.gameOver;
  static String get totalWindRounds => _l10n.totalWindRounds;
  static String get totalRoundsPlayed => _l10n.totalRoundsPlayed;
  static String get totalGames => _l10n.totalGames;
  static String get finishGame => _l10n.finishGame;
  static String get changePosition => _l10n.changePosition;
  static String get swap => _l10n.swap;
  static String get resetGameState => _l10n.resetGameState;
  static String get resetDealer => _l10n.resetDealer;
  static String get resetDealerSubtitle => _l10n.resetDealerSubtitle;
  static String get resetWind => _l10n.resetWind;
  static String get resetWindSubtitle => _l10n.resetWindSubtitle;
  static String get cancelReset => _l10n.cancelReset;
  static String get apply => _l10n.apply;
  static String get currentGameStats => _l10n.currentGameStats;
  static String get noRoundsPlayed => _l10n.noRoundsPlayed;
  static String get mahjongScoringTitle => _l10n.mahjongScoringTitle;
  static String get windEast => _l10n.windEast;
  static String get windSouth => _l10n.windSouth;
  static String get windWest => _l10n.windWest;
  static String get windNorth => _l10n.windNorth;
  static String get calculate => _l10n.calculate;
  static String get noResult => _l10n.noResult;
  static String get mahjong => _l10n.mahjong;
  static String get windCircleSuffix => _l10n.windCircleSuffix;
  static String get tooltipStats => _l10n.tooltipStats;
  static String get tooltipRules => _l10n.tooltipRules;
  static String get tooltipHome => _l10n.tooltipHome;
  static String get loadFailed => _l10n.loadFailed;
  static String get saveFailed => _l10n.saveFailed;
  static String get deleteFailed => _l10n.deleteFailed;
  static String get noInternet => _l10n.noInternet;
  static String get tryAgain => _l10n.tryAgain;
  static String get selectLanguage => _l10n.selectLanguage;
  static String get moreLanguagesComingSoon => _l10n.moreLanguagesComingSoon;
  static String get rulesAndTutorial => _l10n.rulesAndTutorial;
  static String get rulesReference => _l10n.rulesReference;
  static String get mahjongTutorial => _l10n.mahjongTutorial;
  static String get allFan => _l10n.allFan;
  static String get searchRules => _l10n.searchRules;
  static String get tutorialWelcome => _l10n.tutorialWelcome;
  static String get tutorialTiles => _l10n.tutorialTiles;
  static String get tutorialRules => _l10n.tutorialRules;
  static String get rulesTitle => _l10n.rulesTitle;
  static String get tutorialScore => _l10n.tutorialScore;
  static String get previous => _l10n.previous;
  static String get next => _l10n.next;
  static String get viewExample => _l10n.viewExample;
  static String get hideExample => _l10n.hideExample;
  static String get exampleExplanation => _l10n.exampleExplanation;
  static String get welcomeTitle => _l10n.welcomeTitle;
  static String get appDescription => _l10n.appDescription;
  static String get keyFeatures => _l10n.keyFeatures;
  static String get smartCalculatorTitle => _l10n.smartCalculatorTitle;
  static String get smartCalculatorDesc => _l10n.smartCalculatorDesc;
  static String get gameRecordingTitle => _l10n.gameRecordingTitle;
  static String get gameRecordingDesc => _l10n.gameRecordingDesc;
  static String get rulesReferenceTitle => _l10n.rulesReferenceTitle;
  static String get rulesReferenceDesc => _l10n.rulesReferenceDesc;
  static String get playerManagementTitle => _l10n.playerManagementTitle;
  static String get playerManagementDesc => _l10n.playerManagementDesc;
  static String get swipeToLearn => _l10n.swipeToLearn;
  static String get tileTypesTitle => _l10n.tileTypesTitle;
  static String get characterTiles => _l10n.characterTiles;
  static String get characterTilesDesc => _l10n.characterTilesDesc;
  static String get dotsTiles => _l10n.dotsTiles;
  static String get dotsTilesDesc => _l10n.dotsTilesDesc;
  static String get bambooTiles => _l10n.bambooTiles;
  static String get bambooTilesDesc => _l10n.bambooTilesDesc;
  static String get honorTiles => _l10n.honorTiles;
  static String get honorTilesDesc => _l10n.honorTilesDesc;
  static String get flowerTiles => _l10n.flowerTiles;
  static String get flowerTilesDesc => _l10n.flowerTilesDesc;
  static String get basicRulesTitle => _l10n.basicRulesTitle;
  static String get gameObjectiveTitle => _l10n.gameObjectiveTitle;
  static String get gameObjectiveDesc1 => _l10n.gameObjectiveDesc1;
  static String get gameObjectiveDesc2 => _l10n.gameObjectiveDesc2;
  static String get gameObjectiveDesc3 => _l10n.gameObjectiveDesc3;
  static String get basicTermsTitle => _l10n.basicTermsTitle;
  static String get basicTermsChow => _l10n.basicTermsChow;
  static String get basicTermsPong => _l10n.basicTermsPong;
  static String get basicTermsEyes => _l10n.basicTermsEyes;
  static String get basicTermsSelfDraw => _l10n.basicTermsSelfDraw;
  static String get basicTermsDiscard => _l10n.basicTermsDiscard;
  static String get startingGameTitle => _l10n.startingGameTitle;
  static String get startingGameDesc => _l10n.startingGameDesc;
  static String get diceRollTableTitle => _l10n.diceRollTableTitle;
  static String get counterClockwiseCount => _l10n.counterClockwiseCount;
  static String get exampleRoll8 => _l10n.exampleRoll8;
  static String get drawClockwise => _l10n.drawClockwise;
  static String get rememberDirection => _l10n.rememberDirection;
  static String get dealingProcedureTitle => _l10n.dealingProcedureTitle;
  static String get dealStep1 => _l10n.dealStep1;
  static String get dealStep2 => _l10n.dealStep2;
  static String get dealStep3 => _l10n.dealStep3;
  static String get dealStep4 => _l10n.dealStep4;
  static String get dealStep5 => _l10n.dealStep5;
  static String get gameplayProcessTitle => _l10n.gameplayProcessTitle;
  static String get gameplayProcessDesc => _l10n.gameplayProcessDesc;
  static String get standardTurnTitle => _l10n.standardTurnTitle;
  static String get drawAction => _l10n.drawAction;
  static String get actionAction => _l10n.actionAction;
  static String get discardAction => _l10n.discardAction;
  static String get turnStep1 => _l10n.turnStep1;
  static String get turnStep2 => _l10n.turnStep2;
  static String get turnStep3 => _l10n.turnStep3;
  static String get turnStep4 => _l10n.turnStep4;
  static String get interactionsTitle => _l10n.interactionsTitle;
  static String get interactionsDesc => _l10n.interactionsDesc;
  static String get priorityRuleTitle => _l10n.priorityRuleTitle;
  static String get priorityRuleDesc => _l10n.priorityRuleDesc;
  static String get priorityPongWins => _l10n.priorityPongWins;
  static String get missedWinTitle => _l10n.missedWinTitle;
  static String get missedWinDesc => _l10n.missedWinDesc;
  static String get missedWinException => _l10n.missedWinException;
  static String get actionChow => _l10n.actionChow;
  static String get targetLeftPlayer => _l10n.targetLeftPlayer;
  static String get descChowInteract => _l10n.descChowInteract;
  static String get actionPong => _l10n.actionPong;
  static String get targetAnyPlayer => _l10n.targetAnyPlayer;
  static String get descPongInteract => _l10n.descPongInteract;
  static String get actionKong => _l10n.actionKong;
  static String get descKongInteract => _l10n.descKongInteract;
  static String get actionWinInteract => _l10n.actionWinInteract;
  static String get descWinInteract => _l10n.descWinInteract;
  static String get scoringSystemTitle => _l10n.scoringSystemTitle;
  static String get scoringRulesTitle => _l10n.scoringRulesTitle;
  static String get scoringRulesDesc => _l10n.scoringRulesDesc;
  static String get fanPointsHeader => _l10n.fanPointsHeader;
  static String get byDiscardHeader => _l10n.byDiscardHeader;
  static String get bySelfDrawHeader => _l10n.bySelfDrawHeader;
  static String get flowerTilesScoringTitle => _l10n.flowerTilesScoringTitle;
  static String get noFlowersFan => _l10n.noFlowersFan;
  static String get ownFlowerFan => _l10n.ownFlowerFan;
  static String get flowerMapping => _l10n.flowerMapping;
  static String get seat1Flower => _l10n.seat1Flower;
  static String get seat2Flower => _l10n.seat2Flower;
  static String get seat3Flower => _l10n.seat3Flower;
  static String get seat4Flower => _l10n.seat4Flower;
  static String get honorTilesScoringTitle => _l10n.honorTilesScoringTitle;
  static String get dragonPongFan => _l10n.dragonPongFan;
  static String get roundWindPongFan => _l10n.roundWindPongFan;
  static String get seatWindPongFan => _l10n.seatWindPongFan;
  static String get winningPatternsTitle => _l10n.winningPatternsTitle;
  static String get winningPatternsDesc => _l10n.winningPatternsDesc;
  static String get chickenHand => _l10n.chickenHand;
  static String get naMinOne => _l10n.naMinOne;
  static String get limitHand => _l10n.limitHand;
  static String get selectWinningHand => _l10n.selectWinningHand;
  static String get maxTilesAlert => _l10n.maxTilesAlert;
  static String get maxTotalTilesAlert => _l10n.maxTotalTilesAlert;
  static String get minTilesAlert => _l10n.minTilesAlert;
  static String get selectedCount => _l10n.selectedCount;
  static String get clear => _l10n.clear;
  static String get charactersTab => _l10n.charactersTab;
  static String get dotsTab => _l10n.dotsTab;
  static String get bambooTab => _l10n.bambooTab;
  static String get honorsTab => _l10n.honorsTab;
  static String get invalidTileCount => _l10n.invalidTileCount;
  static String get winningHandThirteenOrphans =>
      _l10n.winningHandThirteenOrphans;
  static String get winningHand => _l10n.winningHand;
  static String get winningHandInvalid => _l10n.winningHandInvalid;
  static String get gameHistoryTitle => _l10n.gameHistoryTitle;
  static String get noHistory => _l10n.noHistory;
  static String get dateLabel => _l10n.dateLabel;
  static String get roundsLabel => _l10n.roundsLabel;
  static String get tipTitle => _l10n.tipTitle;
  static String get splashTitle => _l10n.splashTitle;
  static String get splashSubtitle => _l10n.splashSubtitle;
  static String get tipDesc => _l10n.tipDesc;
  static String get importantNoteTitle => _l10n.importantNoteTitle;
  static String get flowerNote => _l10n.flowerNote;
  static String get dragonNote => _l10n.dragonNote;
  static String get diceDealerEast => _l10n.diceDealerEast;
  static String get diceSouthRight => _l10n.diceSouthRight;
  static String get diceWestOpposite => _l10n.diceWestOpposite;
  static String get diceNorthLeft => _l10n.diceNorthLeft;
  static String get loginTitle => _l10n.loginTitle;
  static String get createAccountTitle => _l10n.createAccountTitle;
  static String get emailLabel => _l10n.emailLabel;
  static String get passwordLabel => _l10n.passwordLabel;
  static String get loginButton => _l10n.loginButton;
  static String get createAccountButton => _l10n.createAccountButton;
  static String get noAccountText => _l10n.noAccountText;
  static String get hasAccountText => _l10n.hasAccountText;
  static String get emailRequired => _l10n.emailRequired;
  static String get emailInvalid => _l10n.emailInvalid;
  static String get passwordRequired => _l10n.passwordRequired;
  static String get passwordLengthError => _l10n.passwordLengthError;
  static String get genericError => _l10n.genericError;
  static String get confirmDeleteTitle => _l10n.confirmDeleteTitle;
  static String get savedGroupsTitle => _l10n.savedGroupsTitle;
  static String get noAnySavedGroups => _l10n.noAnySavedGroups;
  static String get editGroup => _l10n.editGroup;
  static String get deleteGroup => _l10n.deleteGroup;
  static String get createdPrefix => _l10n.createdPrefix;
  static String get playersListPrefix => _l10n.playersListPrefix;

  // ── parameterised methods ──────────────────────────────────────
  static String fan(int f) => _l10n.fan(f);
  static String taiCount(int t) => _l10n.taiCount(t);
  static String currentScore(int score) => _l10n.currentScore(score);
  static String totalWin(int score) => _l10n.totalWin(score);
  static String consecutiveDealerCount(int count) =>
      _l10n.consecutiveDealerCount(count);
  static String editPlayerTitle(int index) => _l10n.editPlayerTitle(index);
  static String swapPositionsContent(String p1, String p2) =>
      _l10n.swapPositionsContent(p1, p2);
  static String roundInfo(String wind, int game) => _l10n.roundInfo(wind, game);
  static String gameCount(int count) => _l10n.gameCount(count);
  static String playerCount(int count) => _l10n.playerCount(count);
  static String roundOf(int current, int total) =>
      _l10n.roundOf(current, total);
  static String gameIndex(int index) => _l10n.gameIndex(index);
  static String defaultPlayerName(int index) => _l10n.defaultPlayerName(index);
  static String confirmDeleteContent(String name) =>
      _l10n.confirmDeleteContent(name);
  static String groupDeleted(String name) => _l10n.groupDeleted(name);
  static String defaultGroupName(String timestamp) =>
      _l10n.defaultGroupName(timestamp);

  // ── TW / HK mode labels ──
  static String get twRulesTitle => _l10n.twRulesTitle;
  static String get hkRulesTitle => _l10n.hkRulesTitle;
  static String get hkMode => _l10n.hkMode;
  static String get twMode => _l10n.twMode;

  // ── TW scoring rules ──
  static String get twScoringRulesTitle => _l10n.twScoringRulesTitle;
  static String get twScoringRulesDesc => _l10n.twScoringRulesDesc;
  static String get twTaiHeader => _l10n.twTaiHeader;
  static String get twScoreHeader => _l10n.twScoreHeader;

  // ── TW instant payment rules ──
  static String get twInstantPayTitle => _l10n.twInstantPayTitle;
  static String get twInstantPayDesc => _l10n.twInstantPayDesc;
  static String get twChaseRule => _l10n.twChaseRule;
  static String get twChaseDesc => _l10n.twChaseDesc;
  static String get twConcealedKongPay => _l10n.twConcealedKongPay;
  static String get twConcealedKongPayDesc => _l10n.twConcealedKongPayDesc;
  static String get twFlowerSetPay => _l10n.twFlowerSetPay;
  static String get twFlowerSetPayDesc => _l10n.twFlowerSetPayDesc;
  static String get twFlowerSeasonSetPay => _l10n.twFlowerSeasonSetPay;
  static String get twFlowerSeasonSetPayDesc => _l10n.twFlowerSeasonSetPayDesc;
  static String get twFlowerGroupPay => _l10n.twFlowerGroupPay;
  static String get twFlowerGroupPayDesc => _l10n.twFlowerGroupPayDesc;
  static String get builtInPayment => _l10n.builtInPayment;
  static String get twFalseWinPay => _l10n.twFalseWinPay;
  static String get twFalseWinPayDesc => _l10n.twFalseWinPayDesc;
  static String get twCalledPongPenalty => _l10n.twCalledPongPenalty;
  static String get twCalledPongPenaltyDesc => _l10n.twCalledPongPenaltyDesc;

  // ── TW penalties ──
  static String get twPenaltiesTitle => _l10n.twPenaltiesTitle;
  static String get twPenaltiesDesc => _l10n.twPenaltiesDesc;
  static String get twWinPlacementRule => _l10n.twWinPlacementRule;
  static String get twWinPlacementDesc => _l10n.twWinPlacementDesc;
  static String get twMissedWinRule => _l10n.twMissedWinRule;
  static String get twMissedWinDesc => _l10n.twMissedWinDesc;
  static String get twKongRevealRule => _l10n.twKongRevealRule;
  static String get twKongRevealDesc => _l10n.twKongRevealDesc;
  static String get twDealerMarkerRule => _l10n.twDealerMarkerRule;
  static String get twDealerMarkerDesc => _l10n.twDealerMarkerDesc;
  static String get twFlowerOrderRule => _l10n.twFlowerOrderRule;
  static String get twFlowerOrderDesc => _l10n.twFlowerOrderDesc;

  // ── TW La settlement ──
  static String get twLaSettlementTitle => _l10n.twLaSettlementTitle;
  static String get twLaSettlementDesc => _l10n.twLaSettlementDesc;
  static String get twLaMultiplier => _l10n.twLaMultiplier;
  static String get twLaMultiplierDesc => _l10n.twLaMultiplierDesc;
  static String get twLaReduction => _l10n.twLaReduction;
  static String get twLaReductionDesc => _l10n.twLaReductionDesc;
  static String get twLaStopRule => _l10n.twLaStopRule;
  static String get twLaStopRuleDesc => _l10n.twLaStopRuleDesc;
  static String get twLaStopRuleTitle => _l10n.twLaStopRuleTitle;
  static String twLaStopRuleMessage(
    String playerName,
    int lossCount,
    String streakWinnerName,
  ) => _l10n.twLaStopRuleMessage(playerName, lossCount, streakWinnerName);
  static String get twLaStopRuleContinue => _l10n.twLaStopRuleContinue;
  static String get twLaStopRuleSettle => _l10n.twLaStopRuleSettle;
  static String get twLaApplied => _l10n.twLaApplied;
  static String get twLaMultiplierApplied => _l10n.twLaMultiplierApplied;
  static String get twLaReductionApplied => _l10n.twLaReductionApplied;
  static String get twLaCarryDebt => _l10n.twLaCarryDebt;
  static String get twLaDebtTracker => _l10n.twLaDebtTracker;
  static String get twLaStreakWinner => _l10n.twLaStreakWinner;
  static String get twLaDebtTotal => _l10n.twLaDebtTotal;
  static String get twLaDebtApplied => _l10n.twLaDebtApplied;
  static String get twLaDebtPending => _l10n.twLaDebtPending;
  static String twLaLosses(int count) => _l10n.twLaLosses(count);
  static String get twLaSettled => _l10n.twLaSettled;
  static String get twLaForceSettleAction => _l10n.twLaForceSettleAction;
  static String get twLaNoActiveStreak => _l10n.twLaNoActiveStreak;
  static String twLaStreakRounds(int count) => _l10n.twLaStreakRounds(count);

  // ── TW dealer bonus ──
  static String get twDealerBonusTitle => _l10n.twDealerBonusTitle;
  static String get twDealerBonusDesc => _l10n.twDealerBonusDesc;
  static String get twDealerBonusBase => _l10n.twDealerBonusBase;
  static String get twDealerBonusFormula => _l10n.twDealerBonusFormula;
  static String get twDealerBonusExample1 => _l10n.twDealerBonusExample1;
  static String get twDealerBonusExample2 => _l10n.twDealerBonusExample2;
  static String get twDealerBonusExample3 => _l10n.twDealerBonusExample3;
  static String get twDealerBonusResponsibility =>
      _l10n.twDealerBonusResponsibility;

  static String get twNoStackRule => _l10n.twNoStackRule;

  // ── TW scoring formula ──
  static String get twScoringFormulaTitle => _l10n.twScoringFormulaTitle;
  static String get twScoringFormulaDesc => _l10n.twScoringFormulaDesc;
  static String get twScoringExample => _l10n.twScoringExample;
  static String get twScoringDefault => _l10n.twScoringDefault;

  // ── TW concealed kong rule ──
  static String get twConcealedKongRule => _l10n.twConcealedKongRule;
  static String get twConcealedKongDesc => _l10n.twConcealedKongDesc;
  static String get twConcealedKongExpl => _l10n.twConcealedKongExpl;

  // ── TW new scoring rules ──
  static String get twNoHonors => _l10n.twNoHonors;
  static String get twDescNoHonors => _l10n.twDescNoHonors;
  static String get twExplNoHonors => _l10n.twExplNoHonors;
  static String get twNoHonorsNoFlowers => _l10n.twNoHonorsNoFlowers;
  static String get twDescNoHonorsNoFlowers => _l10n.twDescNoHonorsNoFlowers;
  static String get twExplNoHonorsNoFlowers => _l10n.twExplNoHonorsNoFlowers;
  static String get twNoHonorsNoFlowersPingHu =>
      _l10n.twNoHonorsNoFlowersPingHu;
  static String get twDescNoHonorsNoFlowersPingHu =>
      _l10n.twDescNoHonorsNoFlowersPingHu;
  static String get twExplNoHonorsNoFlowersPingHu =>
      _l10n.twExplNoHonorsNoFlowersPingHu;
  static String get twChickenHand => _l10n.twChickenHand;
  static String get twDescChickenHand => _l10n.twDescChickenHand;
  static String get twExplChickenHand => _l10n.twExplChickenHand;
  static String get twDoublePong => _l10n.twDoublePong;
  static String get twDescDoublePong => _l10n.twDescDoublePong;
  static String get twExplDoublePong => _l10n.twExplDoublePong;
  static String get twFakeSingle => _l10n.twFakeSingle;
  static String get twDescFakeSingle => _l10n.twDescFakeSingle;
  static String get twExplFakeSingle => _l10n.twExplFakeSingle;
  static String get twTrueSingle => _l10n.twTrueSingle;
  static String get twDescTrueSingle => _l10n.twDescTrueSingle;
  static String get twExplTrueSingle => _l10n.twExplTrueSingle;
  static String get twOldYoung => _l10n.twOldYoung;
  static String get twDescOldYoung => _l10n.twDescOldYoung;
  static String get twExplOldYoung => _l10n.twExplOldYoung;
  static String get twExposedKong => _l10n.twExposedKong;
  static String get twDescExposedKong => _l10n.twDescExposedKong;
  static String get twExplExposedKong => _l10n.twExplExposedKong;
  static String get twConcealedKongTai => _l10n.twConcealedKongTai;
  static String get twDescConcealedKongTai => _l10n.twDescConcealedKongTai;
  static String get twExplConcealedKongTai => _l10n.twExplConcealedKongTai;
  static String get twFlowerWin => _l10n.twFlowerWin;
  static String get twDescFlowerWin => _l10n.twDescFlowerWin;
  static String get twExplFlowerWin => _l10n.twExplFlowerWin;
  static String get twKongWin => _l10n.twKongWin;
  static String get twDescKongWin => _l10n.twDescKongWin;
  static String get twExplKongWin => _l10n.twExplKongWin;
  static String get twRobbingKong => _l10n.twRobbingKong;
  static String get twDescRobbingKong => _l10n.twDescRobbingKong;
  static String get twExplRobbingKong => _l10n.twExplRobbingKong;
  static String get twDoubleKongWin => _l10n.twDoubleKongWin;
  static String get twDescDoubleKongWin => _l10n.twDescDoubleKongWin;
  static String get twExplDoubleKongWin => _l10n.twExplDoubleKongWin;
  static String get twRobbingDoubleKong => _l10n.twRobbingDoubleKong;
  static String get twDescRobbingDoubleKong => _l10n.twDescRobbingDoubleKong;
  static String get twExplRobbingDoubleKong => _l10n.twExplRobbingDoubleKong;
  static String get twTwoConcealedPongs => _l10n.twTwoConcealedPongs;
  static String get twDescTwoConcealedPongs => _l10n.twDescTwoConcealedPongs;
  static String get twExplTwoConcealedPongs => _l10n.twExplTwoConcealedPongs;
  static String get twThreeConcealedPongs => _l10n.twThreeConcealedPongs;
  static String get twDescThreeConcealedPongs =>
      _l10n.twDescThreeConcealedPongs;
  static String get twExplThreeConcealedPongs =>
      _l10n.twExplThreeConcealedPongs;
  static String get twFourConcealedPongs => _l10n.twFourConcealedPongs;
  static String get twDescFourConcealedPongs => _l10n.twDescFourConcealedPongs;
  static String get twExplFourConcealedPongs => _l10n.twExplFourConcealedPongs;
  static String get twIdenticalSequenceTwo => _l10n.twIdenticalSequenceTwo;
  static String get twDescIdenticalSequenceTwo =>
      _l10n.twDescIdenticalSequenceTwo;
  static String get twExplIdenticalSequenceTwo =>
      _l10n.twExplIdenticalSequenceTwo;
  static String get twIdenticalSequenceThree => _l10n.twIdenticalSequenceThree;
  static String get twDescIdenticalSequenceThree =>
      _l10n.twDescIdenticalSequenceThree;
  static String get twExplIdenticalSequenceThree =>
      _l10n.twExplIdenticalSequenceThree;
  static String get twIdenticalSequenceFour => _l10n.twIdenticalSequenceFour;
  static String get twDescIdenticalSequenceFour =>
      _l10n.twDescIdenticalSequenceFour;
  static String get twExplIdenticalSequenceFour =>
      _l10n.twExplIdenticalSequenceFour;
  static String get twMixedDoubleSeq => _l10n.twMixedDoubleSeq;
  static String get twDescMixedDoubleSeq => _l10n.twDescMixedDoubleSeq;
  static String get twExplMixedDoubleSeq => _l10n.twExplMixedDoubleSeq;
  static String get twMixedTripleSeq => _l10n.twMixedTripleSeq;
  static String get twDescMixedTripleSeq => _l10n.twDescMixedTripleSeq;
  static String get twExplMixedTripleSeq => _l10n.twExplMixedTripleSeq;
  static String get twFiveIdenticalSeq => _l10n.twFiveIdenticalSeq;
  static String get twDescFiveIdenticalSeq => _l10n.twDescFiveIdenticalSeq;
  static String get twExplFiveIdenticalSeq => _l10n.twExplFiveIdenticalSeq;
  static String get twTwoBrothers => _l10n.twTwoBrothers;
  static String get twDescTwoBrothers => _l10n.twDescTwoBrothers;
  static String get twExplTwoBrothers => _l10n.twExplTwoBrothers;
  static String get twSmallThreeBrothers => _l10n.twSmallThreeBrothers;
  static String get twDescSmallThreeBrothers => _l10n.twDescSmallThreeBrothers;
  static String get twExplSmallThreeBrothers => _l10n.twExplSmallThreeBrothers;
  static String get twBigThreeBrothers => _l10n.twBigThreeBrothers;
  static String get twDescBigThreeBrothers => _l10n.twDescBigThreeBrothers;
  static String get twExplBigThreeBrothers => _l10n.twExplBigThreeBrothers;
  static String get twSmallThreeSisters => _l10n.twSmallThreeSisters;
  static String get twDescSmallThreeSisters => _l10n.twDescSmallThreeSisters;
  static String get twExplSmallThreeSisters => _l10n.twExplSmallThreeSisters;
  static String get twBigThreeSisters => _l10n.twBigThreeSisters;
  static String get twDescBigThreeSisters => _l10n.twDescBigThreeSisters;
  static String get twExplBigThreeSisters => _l10n.twExplBigThreeSisters;
  static String get twFourToOne => _l10n.twFourToOne;
  static String get twDescFourToOne => _l10n.twDescFourToOne;
  static String get twExplFourToOne => _l10n.twExplFourToOne;
  static String get twFourToTwo => _l10n.twFourToTwo;
  static String get twDescFourToTwo => _l10n.twDescFourToTwo;
  static String get twExplFourToTwo => _l10n.twExplFourToTwo;
  static String get twFourToFour => _l10n.twFourToFour;
  static String get twDescFourToFour => _l10n.twDescFourToFour;
  static String get twExplFourToFour => _l10n.twExplFourToFour;
  static String get twExposedDragon => _l10n.twExposedDragon;
  static String get twDescExposedDragon => _l10n.twDescExposedDragon;
  static String get twExplExposedDragon => _l10n.twExplExposedDragon;
  static String get twExposedMixedDragon => _l10n.twExposedMixedDragon;
  static String get twDescExposedMixedDragon => _l10n.twDescExposedMixedDragon;
  static String get twExplExposedMixedDragon => _l10n.twExplExposedMixedDragon;
  static String get twConcealedMixedDragon => _l10n.twConcealedMixedDragon;
  static String get twDescConcealedMixedDragon =>
      _l10n.twDescConcealedMixedDragon;
  static String get twExplConcealedMixedDragon =>
      _l10n.twExplConcealedMixedDragon;
  static String get twFiveGates => _l10n.twFiveGates;
  static String get twDescFiveGates => _l10n.twDescFiveGates;
  static String get twExplFiveGates => _l10n.twExplFiveGates;
  static String get twMissingOneSuit => _l10n.twMissingOneSuit;
  static String get twDescMissingOneSuit => _l10n.twDescMissingOneSuit;
  static String get twExplMissingOneSuit => _l10n.twExplMissingOneSuit;
  static String get twAllRevealed => _l10n.twAllRevealed;
  static String get twDescAllRevealed => _l10n.twDescAllRevealed;
  static String get twExplAllRevealed => _l10n.twExplAllRevealed;
  static String get twHalfRevealed => _l10n.twHalfRevealed;
  static String get twDescHalfRevealed => _l10n.twDescHalfRevealed;
  static String get twExplHalfRevealed => _l10n.twExplHalfRevealed;
  static String get twLastSevenTiles => _l10n.twLastSevenTiles;
  static String get twDescLastSevenTiles => _l10n.twDescLastSevenTiles;
  static String get twExplLastSevenTiles => _l10n.twExplLastSevenTiles;
  static String get twLastTenTiles => _l10n.twLastTenTiles;
  static String get twDescLastTenTiles => _l10n.twDescLastTenTiles;
  static String get twExplLastTenTiles => _l10n.twExplLastTenTiles;
  static String get twSmallThreeWinds => _l10n.twSmallThreeWinds;
  static String get twDescSmallThreeWinds => _l10n.twDescSmallThreeWinds;
  static String get twExplSmallThreeWinds => _l10n.twExplSmallThreeWinds;
  static String get twBigThreeWinds => _l10n.twBigThreeWinds;
  static String get twDescBigThreeWinds => _l10n.twDescBigThreeWinds;
  static String get twExplBigThreeWinds => _l10n.twExplBigThreeWinds;
  static String get twSixteenNonMatching => _l10n.twSixteenNonMatching;
  static String get twDescSixteenNonMatching => _l10n.twDescSixteenNonMatching;
  static String get twExplSixteenNonMatching => _l10n.twExplSixteenNonMatching;
  static String get twOneFlowerSet => _l10n.twOneFlowerSet;
  static String get twDescOneFlowerSet => _l10n.twDescOneFlowerSet;
  static String get twExplOneFlowerSet => _l10n.twExplOneFlowerSet;
  static String get twTwoFlowerSets => _l10n.twTwoFlowerSets;
  static String get twDescTwoFlowerSets => _l10n.twDescTwoFlowerSets;
  static String get twExplTwoFlowerSets => _l10n.twExplTwoFlowerSets;
  static String get twMixedTerminalsPongs => _l10n.twMixedTerminalsPongs;
  static String get twDescMixedTerminalsPongs =>
      _l10n.twDescMixedTerminalsPongs;
  static String get twExplMixedTerminalsPongs =>
      _l10n.twExplMixedTerminalsPongs;
  static String get twPureTerminalsTw => _l10n.twPureTerminalsTw;
  static String get twDescPureTerminalsTw => _l10n.twDescPureTerminalsTw;
  static String get twExplPureTerminalsTw => _l10n.twExplPureTerminalsTw;
  static String get twMixedTerminalChows => _l10n.twMixedTerminalChows;
  static String get twDescMixedTerminalChows => _l10n.twDescMixedTerminalChows;
  static String get twExplMixedTerminalChows => _l10n.twExplMixedTerminalChows;
  static String get twPureTerminalChows => _l10n.twPureTerminalChows;
  static String get twDescPureTerminalChows => _l10n.twDescPureTerminalChows;
  static String get twExplPureTerminalChows => _l10n.twExplPureTerminalChows;
  static String get twHumanWin => _l10n.twHumanWin;
  static String get twDescHumanWin => _l10n.twDescHumanWin;
  static String get twExplHumanWin => _l10n.twExplHumanWin;
  static String get twSevenRobOne => _l10n.twSevenRobOne;
  static String get twDescSevenRobOne => _l10n.twDescSevenRobOne;
  static String get twExplSevenRobOne => _l10n.twExplSevenRobOne;
  static String get twHeavenlyReady => _l10n.twHeavenlyReady;
  static String get twDescHeavenlyReady => _l10n.twDescHeavenlyReady;
  static String get twExplHeavenlyReady => _l10n.twExplHeavenlyReady;
  static String get twEarthlyReady => _l10n.twEarthlyReady;
  static String get twDescEarthlyReady => _l10n.twDescEarthlyReady;
  static String get twExplEarthlyReady => _l10n.twExplEarthlyReady;
  static String get twMiguiTw => _l10n.twMiguiTw;
  static String get twDescMiguiTw => _l10n.twDescMiguiTw;
  static String get twExplMiguiTw => _l10n.twExplMiguiTw;

  // ── TW stacking rules ──
  static String get twStackRulesTitle => _l10n.twStackRulesTitle;
  static String get twStackRulesDesc => _l10n.twStackRulesDesc;
  static String get twStackRule1 => _l10n.twStackRule1;
  static String get twStackRule2 => _l10n.twStackRule2;
  static String get twStackRule3 => _l10n.twStackRule3;
  static String get twStackRule4 => _l10n.twStackRule4;
  static String get twStackRule5 => _l10n.twStackRule5;
  static String get twStackRule6 => _l10n.twStackRule6;
  static String get twStackRule7 => _l10n.twStackRule7;

  // ── Achievement system ──
  static String get achvTitle => _l10n.achvTitle;

  /// Dynamic key lookup for achievement title/description keys.
  /// Falls back to the key itself if not found.
  static String getString(String key) => _achvKeyMap[key]?.call() ?? key;

  static final Map<String, String Function()> _achvKeyMap = {
    'achvGenFirstGameTitle': () => _l10n.achvGenFirstGameTitle,
    'achvGenFirstGameDesc': () => _l10n.achvGenFirstGameDesc,
    'achvGenTenGamesTitle': () => _l10n.achvGenTenGamesTitle,
    'achvGenTenGamesDesc': () => _l10n.achvGenTenGamesDesc,
    'achvGenHundredGamesTitle': () => _l10n.achvGenHundredGamesTitle,
    'achvGenHundredGamesDesc': () => _l10n.achvGenHundredGamesDesc,
    'achvGenFirstWinTitle': () => _l10n.achvGenFirstWinTitle,
    'achvGenFirstWinDesc': () => _l10n.achvGenFirstWinDesc,
    'achvGenWinStreak3Title': () => _l10n.achvGenWinStreak3Title,
    'achvGenWinStreak3Desc': () => _l10n.achvGenWinStreak3Desc,
    'achvGenWinStreak5Title': () => _l10n.achvGenWinStreak5Title,
    'achvGenWinStreak5Desc': () => _l10n.achvGenWinStreak5Desc,
    'achvGenSelfDraw10Title': () => _l10n.achvGenSelfDraw10Title,
    'achvGenSelfDraw10Desc': () => _l10n.achvGenSelfDraw10Desc,
    'achvGenSelfDraw50Title': () => _l10n.achvGenSelfDraw50Title,
    'achvGenSelfDraw50Desc': () => _l10n.achvGenSelfDraw50Desc,
    'achvGenDealerStreak3Title': () => _l10n.achvGenDealerStreak3Title,
    'achvGenDealerStreak3Desc': () => _l10n.achvGenDealerStreak3Desc,
    'achvGenNeverDealInTitle': () => _l10n.achvGenNeverDealInTitle,
    'achvGenNeverDealInDesc': () => _l10n.achvGenNeverDealInDesc,
    'achvGenComebackTitle': () => _l10n.achvGenComebackTitle,
    'achvGenComebackDesc': () => _l10n.achvGenComebackDesc,
    'achvHkFirstWinTitle': () => _l10n.achvHkFirstWinTitle,
    'achvHkFirstWinDesc': () => _l10n.achvHkFirstWinDesc,
    'achvHkFan3Title': () => _l10n.achvHkFan3Title,
    'achvHkFan3Desc': () => _l10n.achvHkFan3Desc,
    'achvHkFullFlushTitle': () => _l10n.achvHkFullFlushTitle,
    'achvHkFullFlushDesc': () => _l10n.achvHkFullFlushDesc,
    'achvHkAllPongs5Title': () => _l10n.achvHkAllPongs5Title,
    'achvHkAllPongs5Desc': () => _l10n.achvHkAllPongs5Desc,
    'achvHkBigThreeDragonsTitle': () => _l10n.achvHkBigThreeDragonsTitle,
    'achvHkBigThreeDragonsDesc': () => _l10n.achvHkBigThreeDragonsDesc,
    'achvHkBigFourWindsTitle': () => _l10n.achvHkBigFourWindsTitle,
    'achvHkBigFourWindsDesc': () => _l10n.achvHkBigFourWindsDesc,
    'achvHkThirteenOrphansTitle': () => _l10n.achvHkThirteenOrphansTitle,
    'achvHkThirteenOrphansDesc': () => _l10n.achvHkThirteenOrphansDesc,
    'achvHkNineGatesTitle': () => _l10n.achvHkNineGatesTitle,
    'achvHkNineGatesDesc': () => _l10n.achvHkNineGatesDesc,
    'achvHkConcealedHand10Title': () => _l10n.achvHkConcealedHand10Title,
    'achvHkConcealedHand10Desc': () => _l10n.achvHkConcealedHand10Desc,
    'achvHkLastTileWinTitle': () => _l10n.achvHkLastTileWinTitle,
    'achvHkLastTileWinDesc': () => _l10n.achvHkLastTileWinDesc,
    'achvHkRobbingKongTitle': () => _l10n.achvHkRobbingKongTitle,
    'achvHkRobbingKongDesc': () => _l10n.achvHkRobbingKongDesc,
    'achvHkMaxFanTitle': () => _l10n.achvHkMaxFanTitle,
    'achvHkMaxFanDesc': () => _l10n.achvHkMaxFanDesc,
    'achvTwFirstWinTitle': () => _l10n.achvTwFirstWinTitle,
    'achvTwFirstWinDesc': () => _l10n.achvTwFirstWinDesc,
    'achvTwTai10Title': () => _l10n.achvTwTai10Title,
    'achvTwTai10Desc': () => _l10n.achvTwTai10Desc,
    'achvTwTai30Title': () => _l10n.achvTwTai30Title,
    'achvTwTai30Desc': () => _l10n.achvTwTai30Desc,
    'achvTwTai80Title': () => _l10n.achvTwTai80Title,
    'achvTwTai80Desc': () => _l10n.achvTwTai80Desc,
    'achvTwCommonHand10Title': () => _l10n.achvTwCommonHand10Title,
    'achvTwCommonHand10Desc': () => _l10n.achvTwCommonHand10Desc,
    'achvTwConcealedSelfDrawn5Title': () =>
        _l10n.achvTwConcealedSelfDrawn5Title,
    'achvTwConcealedSelfDrawn5Desc': () => _l10n.achvTwConcealedSelfDrawn5Desc,
    'achvTwDealerStreak5Title': () => _l10n.achvTwDealerStreak5Title,
    'achvTwDealerStreak5Desc': () => _l10n.achvTwDealerStreak5Desc,
    'achvTwKongWinTitle': () => _l10n.achvTwKongWinTitle,
    'achvTwKongWinDesc': () => _l10n.achvTwKongWinDesc,
    'achvTwFlowerWinTitle': () => _l10n.achvTwFlowerWinTitle,
    'achvTwFlowerWinDesc': () => _l10n.achvTwFlowerWinDesc,
    'achvTwSevenRobOneTitle': () => _l10n.achvTwSevenRobOneTitle,
    'achvTwSevenRobOneDesc': () => _l10n.achvTwSevenRobOneDesc,
    'achvTwHeavenlyListenTitle': () => _l10n.achvTwHeavenlyListenTitle,
    'achvTwHeavenlyListenDesc': () => _l10n.achvTwHeavenlyListenDesc,
    'achvTwChickenHand10Title': () => _l10n.achvTwChickenHand10Title,
    'achvTwChickenHand10Desc': () => _l10n.achvTwChickenHand10Desc,
    'achvTwLikulikuTitle': () => _l10n.achvTwLikulikuTitle,
    'achvTwLikulikuDesc': () => _l10n.achvTwLikulikuDesc,
    'achvMsWins100Title': () => _l10n.achvMsWins100Title,
    'achvMsWins100Desc': () => _l10n.achvMsWins100Desc,
    'achvMsWins500Title': () => _l10n.achvMsWins500Title,
    'achvMsWins500Desc': () => _l10n.achvMsWins500Desc,
    'achvMsScore10000Title': () => _l10n.achvMsScore10000Title,
    'achvMsScore10000Desc': () => _l10n.achvMsScore10000Desc,
    'achvMsScore100000Title': () => _l10n.achvMsScore100000Title,
    'achvMsScore100000Desc': () => _l10n.achvMsScore100000Desc,
    'achvMsDualModeTitle': () => _l10n.achvMsDualModeTitle,
    'achvMsDualModeDesc': () => _l10n.achvMsDualModeDesc,
  };
  static String get achvUnlocked => _l10n.achvUnlocked;
  static String get achvLocked => _l10n.achvLocked;
  static String achvProgress(String current, String target) =>
      _l10n.achvProgress(current, target);
  static String achvUnlockedAt(String date) => _l10n.achvUnlockedAt(date);
  static String get achvNewUnlock => _l10n.achvNewUnlock;
  static String get achvViewAll => _l10n.achvViewAll;
  static String get achvTabAll => _l10n.achvTabAll;
  static String get achvTabGeneral => _l10n.achvTabGeneral;
  static String get achvTabHk => _l10n.achvTabHk;
  static String get achvTabTw => _l10n.achvTabTw;
  static String get achvTabMilestone => _l10n.achvTabMilestone;
  static String get achvTierBronze => _l10n.achvTierBronze;
  static String get achvTierSilver => _l10n.achvTierSilver;
  static String get achvTierGold => _l10n.achvTierGold;
  static String get achvTierDiamond => _l10n.achvTierDiamond;
  static String achvSummary(String unlocked, String total) =>
      _l10n.achvSummary(unlocked, total);

  // ── General achievements ──
  static String get achvGenFirstGameTitle => _l10n.achvGenFirstGameTitle;
  static String get achvGenFirstGameDesc => _l10n.achvGenFirstGameDesc;
  static String get achvGenTenGamesTitle => _l10n.achvGenTenGamesTitle;
  static String get achvGenTenGamesDesc => _l10n.achvGenTenGamesDesc;
  static String get achvGenHundredGamesTitle => _l10n.achvGenHundredGamesTitle;
  static String get achvGenHundredGamesDesc => _l10n.achvGenHundredGamesDesc;
  static String get achvGenFirstWinTitle => _l10n.achvGenFirstWinTitle;
  static String get achvGenFirstWinDesc => _l10n.achvGenFirstWinDesc;
  static String get achvGenWinStreak3Title => _l10n.achvGenWinStreak3Title;
  static String get achvGenWinStreak3Desc => _l10n.achvGenWinStreak3Desc;
  static String get achvGenWinStreak5Title => _l10n.achvGenWinStreak5Title;
  static String get achvGenWinStreak5Desc => _l10n.achvGenWinStreak5Desc;
  static String get achvGenSelfDraw10Title => _l10n.achvGenSelfDraw10Title;
  static String get achvGenSelfDraw10Desc => _l10n.achvGenSelfDraw10Desc;
  static String get achvGenSelfDraw50Title => _l10n.achvGenSelfDraw50Title;
  static String get achvGenSelfDraw50Desc => _l10n.achvGenSelfDraw50Desc;
  static String get achvGenDealerStreak3Title =>
      _l10n.achvGenDealerStreak3Title;
  static String get achvGenDealerStreak3Desc => _l10n.achvGenDealerStreak3Desc;
  static String get achvGenNeverDealInTitle => _l10n.achvGenNeverDealInTitle;
  static String get achvGenNeverDealInDesc => _l10n.achvGenNeverDealInDesc;
  static String get achvGenComebackTitle => _l10n.achvGenComebackTitle;
  static String get achvGenComebackDesc => _l10n.achvGenComebackDesc;

  // ── HK achievements ──
  static String get achvHkFirstWinTitle => _l10n.achvHkFirstWinTitle;
  static String get achvHkFirstWinDesc => _l10n.achvHkFirstWinDesc;
  static String get achvHkFan3Title => _l10n.achvHkFan3Title;
  static String get achvHkFan3Desc => _l10n.achvHkFan3Desc;
  static String get achvHkFullFlushTitle => _l10n.achvHkFullFlushTitle;
  static String get achvHkFullFlushDesc => _l10n.achvHkFullFlushDesc;
  static String get achvHkAllPongs5Title => _l10n.achvHkAllPongs5Title;
  static String get achvHkAllPongs5Desc => _l10n.achvHkAllPongs5Desc;
  static String get achvHkBigThreeDragonsTitle =>
      _l10n.achvHkBigThreeDragonsTitle;
  static String get achvHkBigThreeDragonsDesc =>
      _l10n.achvHkBigThreeDragonsDesc;
  static String get achvHkBigFourWindsTitle => _l10n.achvHkBigFourWindsTitle;
  static String get achvHkBigFourWindsDesc => _l10n.achvHkBigFourWindsDesc;
  static String get achvHkThirteenOrphansTitle =>
      _l10n.achvHkThirteenOrphansTitle;
  static String get achvHkThirteenOrphansDesc =>
      _l10n.achvHkThirteenOrphansDesc;
  static String get achvHkNineGatesTitle => _l10n.achvHkNineGatesTitle;
  static String get achvHkNineGatesDesc => _l10n.achvHkNineGatesDesc;
  static String get achvHkConcealedHand10Title =>
      _l10n.achvHkConcealedHand10Title;
  static String get achvHkConcealedHand10Desc =>
      _l10n.achvHkConcealedHand10Desc;
  static String get achvHkLastTileWinTitle => _l10n.achvHkLastTileWinTitle;
  static String get achvHkLastTileWinDesc => _l10n.achvHkLastTileWinDesc;
  static String get achvHkRobbingKongTitle => _l10n.achvHkRobbingKongTitle;
  static String get achvHkRobbingKongDesc => _l10n.achvHkRobbingKongDesc;
  static String get achvHkMaxFanTitle => _l10n.achvHkMaxFanTitle;
  static String get achvHkMaxFanDesc => _l10n.achvHkMaxFanDesc;

  // ── TW achievements ──
  static String get achvTwFirstWinTitle => _l10n.achvTwFirstWinTitle;
  static String get achvTwFirstWinDesc => _l10n.achvTwFirstWinDesc;
  static String get achvTwTai10Title => _l10n.achvTwTai10Title;
  static String get achvTwTai10Desc => _l10n.achvTwTai10Desc;
  static String get achvTwTai30Title => _l10n.achvTwTai30Title;
  static String get achvTwTai30Desc => _l10n.achvTwTai30Desc;
  static String get achvTwTai80Title => _l10n.achvTwTai80Title;
  static String get achvTwTai80Desc => _l10n.achvTwTai80Desc;
  static String get achvTwCommonHand10Title => _l10n.achvTwCommonHand10Title;
  static String get achvTwCommonHand10Desc => _l10n.achvTwCommonHand10Desc;
  static String get achvTwConcealedSelfDrawn5Title =>
      _l10n.achvTwConcealedSelfDrawn5Title;
  static String get achvTwConcealedSelfDrawn5Desc =>
      _l10n.achvTwConcealedSelfDrawn5Desc;
  static String get achvTwDealerStreak5Title => _l10n.achvTwDealerStreak5Title;
  static String get achvTwDealerStreak5Desc => _l10n.achvTwDealerStreak5Desc;
  static String get achvTwKongWinTitle => _l10n.achvTwKongWinTitle;
  static String get achvTwKongWinDesc => _l10n.achvTwKongWinDesc;
  static String get achvTwFlowerWinTitle => _l10n.achvTwFlowerWinTitle;
  static String get achvTwFlowerWinDesc => _l10n.achvTwFlowerWinDesc;
  static String get achvTwSevenRobOneTitle => _l10n.achvTwSevenRobOneTitle;
  static String get achvTwSevenRobOneDesc => _l10n.achvTwSevenRobOneDesc;
  static String get achvTwHeavenlyListenTitle =>
      _l10n.achvTwHeavenlyListenTitle;
  static String get achvTwHeavenlyListenDesc => _l10n.achvTwHeavenlyListenDesc;
  static String get achvTwChickenHand10Title => _l10n.achvTwChickenHand10Title;
  static String get achvTwChickenHand10Desc => _l10n.achvTwChickenHand10Desc;
  static String get achvTwLikulikuTitle => _l10n.achvTwLikulikuTitle;
  static String get achvTwLikulikuDesc => _l10n.achvTwLikulikuDesc;

  // ── Milestone achievements ──
  static String get achvMsWins100Title => _l10n.achvMsWins100Title;
  static String get achvMsWins100Desc => _l10n.achvMsWins100Desc;
  static String get achvMsWins500Title => _l10n.achvMsWins500Title;
  static String get achvMsWins500Desc => _l10n.achvMsWins500Desc;
  static String get achvMsScore10000Title => _l10n.achvMsScore10000Title;
  static String get achvMsScore10000Desc => _l10n.achvMsScore10000Desc;
  static String get achvMsScore100000Title => _l10n.achvMsScore100000Title;
  static String get achvMsScore100000Desc => _l10n.achvMsScore100000Desc;
  static String get achvMsDualModeTitle => _l10n.achvMsDualModeTitle;
  static String get achvMsDualModeDesc => _l10n.achvMsDualModeDesc;

  // ── Home screen: hero banner / quick start / daily tips ──
  static String get continueLastGame => _l10n.continueLastGame;
  static String get greetingMorning => _l10n.greetingMorning;
  static String get greetingAfternoon => _l10n.greetingAfternoon;
  static String get greetingEvening => _l10n.greetingEvening;
  static String get quickStart => _l10n.quickStart;
  static String get hkQuickStart => _l10n.hkQuickStart;
  static String get twQuickStart => _l10n.twQuickStart;
  static String get dailyTipLabel => _l10n.dailyTipLabel;
  static String get tipDayTitle1 => _l10n.tipDayTitle1;
  static String get tipDayContent1 => _l10n.tipDayContent1;
  static String get tipDayTitle2 => _l10n.tipDayTitle2;
  static String get tipDayContent2 => _l10n.tipDayContent2;
  static String get tipDayTitle3 => _l10n.tipDayTitle3;
  static String get tipDayContent3 => _l10n.tipDayContent3;
  static String get tipDayTitle4 => _l10n.tipDayTitle4;
  static String get tipDayContent4 => _l10n.tipDayContent4;
  static String get tipDayTitle5 => _l10n.tipDayTitle5;
  static String get tipDayContent5 => _l10n.tipDayContent5;
  static String get tipDayTitle6 => _l10n.tipDayTitle6;
  static String get tipDayContent6 => _l10n.tipDayContent6;
  static String get tipDayTitle7 => _l10n.tipDayTitle7;
  static String get tipDayContent7 => _l10n.tipDayContent7;
  static String get tipDayTitle8 => _l10n.tipDayTitle8;
  static String get tipDayContent8 => _l10n.tipDayContent8;
  static String get tipDayTitle9 => _l10n.tipDayTitle9;
  static String get tipDayContent9 => _l10n.tipDayContent9;
  static String get tipDayTitle10 => _l10n.tipDayTitle10;
  static String get tipDayContent10 => _l10n.tipDayContent10;

  // ── manual: fanCount uses string replacement (not ARB-compatible) ──
  static String fanCount(String count) {
    if (_l10n is L10nZh) return count.replaceAll('Fan', '番');
    return count;
  }

  // ── Settings: new options ──
  static String get customFanValues => _l10n.customFanValues;
  static String get customFanValuesDesc => _l10n.customFanValuesDesc;
  static String get customHkFan => _l10n.customHkFan;
  static String get customTwTai => _l10n.customTwTai;
  static String get resetToDefault => _l10n.resetToDefault;
  static String get resetFanConfirm => _l10n.resetFanConfirm;
  static String get customized => _l10n.customized;
  static String defaultValue(int value) => _l10n.defaultValue(value);
  static String get gamePreferences => _l10n.gamePreferences;
  static String get displaySettings => _l10n.displaySettings;
  static String get advancedSettings => _l10n.advancedSettings;
  static String get accountSettings => _l10n.accountSettings;
  static String get noCustomizations => _l10n.noCustomizations;
  static String get editFanValue => _l10n.editFanValue;
  static String get editTaiValue => _l10n.editTaiValue;
  static String get enterNewValue => _l10n.enterNewValue;
  static String get enterNewTaiValue => _l10n.enterNewTaiValue;
  static String get invalidValue => _l10n.invalidValue;
  static String get customFanSaved => _l10n.customFanSaved;
  static String get allReset => _l10n.allReset;
  static String get hkGameSettings => _l10n.hkGameSettings;
  static String get twGameSettings => _l10n.twGameSettings;
  static String get hkMinFanSetting => _l10n.hkMinFan;
  static String get hkMaxFanSetting => _l10n.hkMaxFan;
  static String get twBaseTaiSetting => _l10n.twBaseTaiSetting;
  static String get twTaiValueSetting => _l10n.twTaiValueSetting;
  static String get addRule => _l10n.addRule;
  static String get deleteRule => _l10n.deleteRule;
  static String get ruleName => _l10n.ruleName;
  static String get fanValueLabel => _l10n.fanValueLabel;
  static String get taiValueLabel => _l10n.taiValueLabel;
  static String get addCustomRule => _l10n.addCustomRule;
  static String get deleteConfirm => _l10n.deleteConfirm;
  static String get ruleDeleted => _l10n.ruleDeleted;
  static String get ruleAdded => _l10n.ruleAdded;
  static String get ruleRestored => _l10n.ruleRestored;
  static String get deletedRules => _l10n.deletedRules;
  static String get restore => _l10n.restore;
  static String get customRules => _l10n.customRules;
  static String get builtInRules => _l10n.builtInRules;
  static String get twPayments => _l10n.twPayments;
  static String get twPaymentsDesc => _l10n.twPaymentsDesc;
  static String get paymentName => _l10n.paymentName;
  static String get paymentValue => _l10n.paymentValue;
  static String get addPayment => _l10n.addPayment;
  static String get editPayment => _l10n.editPayment;
  static String get noPayments => _l10n.noPayments;
  static String get paymentSaved => _l10n.paymentSaved;
  static String get paymentDeleted => _l10n.paymentDeleted;
  static String get enterRuleName => _l10n.enterRuleName;
  static String get enterValue => _l10n.enterValue;
  static String get instantPayment => _l10n.instantPayment;
  static String get selectPayer => _l10n.selectPayer;
  static String get selectReceiver => _l10n.selectReceiver;
  static String get selectPaymentItem => _l10n.selectPaymentItem;
  static String get paymentAmount => _l10n.paymentAmount;
  static String get paymentApplied => _l10n.paymentApplied;
  static String get allOtherPlayers => _l10n.allOtherPlayers;
  static String get customAmount => _l10n.customAmount;
  static String get achvTwInstantPay5Title => _l10n.achvTwInstantPay5Title;
  static String get achvTwInstantPay5Desc => _l10n.achvTwInstantPay5Desc;
  static String get achvTwInstantPay20Title => _l10n.achvTwInstantPay20Title;
  static String get achvTwInstantPay20Desc => _l10n.achvTwInstantPay20Desc;
  static String userSetFan(int f) => _l10n.userSetFan(f);
  static String userSetTai(int f) => _l10n.userSetTai(f);
  static String get roundHistory => _l10n.roundHistory;

  // ── Player setup redesign ──
  static String get seatOrder => _l10n.seatOrder;
  static String get dragToReorder => _l10n.dragToReorder;
  static String get recentPlayers => _l10n.recentPlayers;
  static String get duplicateNameWarning => _l10n.duplicateNameWarning;
  static String windSeat(String wind) => _l10n.windSeat(wind);
  static String get tapToEdit => _l10n.tapToEdit;
  static String get playerSetupSubtitle => _l10n.playerSetupSubtitle;
  static String get clearName => _l10n.clearName;
}
